name: Production deployment

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client/

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: './client/package-lock.json'
      - name: Installing dependencies
        run: npm ci
      - name: Building client
        env:
          REACT_APP_API_BASE_URL: http://3.145.115.170/api
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: published-artifact
          run: pwd && ls -al 
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: published-artifact
          path: ./dist
      - name: Current directory details
        run: pwd && ls
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./dist/*"
          REMOTE_HOST: ${{ secrets.PRODUCTION_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          # TARGET: ${{ secrets.TARGET }}
          TARGET: /var/www/app/
          SCRIPT_AFTER: |
            whoami
            ls -al
            sudo chown -R www-data:www-data /var/www/app
            sudo systemctl restart nginx
