name: Bus Booking App CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: React application building
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client/

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./client/package-lock.json"
      - name: Installing dependencies
        run: npm ci
      - name: Building client
        env:
          REACT_APP_API_BASE_URL: http://3.145.115.170/api
        run: npm run build
      - name: File list
        run: pwd && ls -al


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: published-artifact
          path: client/dist/

  deploy:
    name: React application deploying to server
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: published-artifact
          path: client/dist/
      - name: Current directory details
        run: pwd && ls


      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "client/dist/*"
          REMOTE_HOST: ${{ secrets.PRODUCTION_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: /home/ubuntu/client/
          SCRIPT_AFTER: |
            whoami
            ls -al
            sudo cp -R /home/ubuntu/client/* /var/www/app/
            sudo chown -R www-data:www-data /var/www/app
            sudo rm -rf /home/ubuntu/client/* 
            sudo systemctl restart nginx


  server:
    name: Backend setup to the server
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server/

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Current directory details
        run: pwd && ls -al
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./server/package-lock.json"
      - name: Installing dependencies
        run: npm ci
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "server/*"
          REMOTE_HOST: ${{ secrets.PRODUCTION_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: /home/ubuntu/server/
          SCRIPT_AFTER: |
            whoami
            ls -al
            pm2 stop 0
            pm2 delete 0
            pm2 start /home/ubuntu/server/index.js
            sudo systemctl restart nginx
